name: Setup DBT
description: Prepare dbt environment

runs:
  using: "composite"
  steps:
    - name: Setup Python + dependencies
      uses: ./.github/actions/setup-python

    - name: Install dbt (fallback if not in requirements)
      shell: bash
      run: |
        pip install dbt-core dbt-bigquery

    - name: Install dbt dependencies
      shell: bash
      run: dbt deps