name: Setup dbt Environment
description: Prepare dbt environment

runs:
  using: "composite"
  steps:
    - name: Setup Python and dependencies
      uses: ./.github/actions/setup-python

    - name: Install dbt packages
      shell: bash
      run: dbt deps