name: Test GCP Auth

on:
  workflow_dispatch:

jobs:
  auth-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/52586954053/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-sa@exalted-bonus-488516-k0.iam.gserviceaccount.com"

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Test authentication
        run: bq ls --project_id=exalted-bonus-488516-k0
