name: Scheduled Run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1-5"  # Segunda a sexta à meia-noite UTC

permissions:
  id-token: write
  contents: read

jobs:
  run-dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup DBT
        uses: ./.github/actions/setup-dbt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/52586954053/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-sa@exalted-bonus-488516-k0.iam.gserviceaccount.com"

      - name: Run dbt build (prod)
        run: dbt build --target prod
